import type { SearchResult } from "@/lib/types";
import type { BackendGraph } from "@/lib/api/backend";

export function exportSearchMarkdown(result: SearchResult): string {
  const lines = [
    `# R&D Knowledge Map — Query Report`,
    ``,
    `**Query:** ${result.query}`,
    ``,
    `## Answer`,
    result.narrative || "_No answer generated._",
    ``,
  ];
  if (result.confidence != null) {
    lines.push(`**Confidence:** ${Math.round(result.confidence * 100)}%`, ``);
  }
  if (result.sources.length) {
    lines.push(`## Sources`, ``);
    for (const s of result.sources) {
      lines.push(`### [${s.index}] ${s.title || s.documentId}`, ``, s.text, ``);
    }
  }
  if (result.gaps.length) {
    lines.push(`## Data gaps`, ``);
    for (const g of result.gaps) {
      lines.push(`- **${g.material}** · ${g.mode} · ${g.property}: ${g.reason}`);
    }
    lines.push(``);
  }
  lines.push(`---`, `_Generated by Scientific Tangle R&D Knowledge Map_`);
  return lines.join("\n");
}

export function downloadText(filename: string, content: string, mime = "text/plain") {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function exportSearchJson(result: SearchResult, graph?: BackendGraph) {
  return JSON.stringify({ query: result.query, result, graph }, null, 2);
}
